### ISSUE TITLE
--commands-file option is being written to the tree file

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-prepare#17]
The `--commands-file` option is being written to the tree file, so if this option is added/changed/removed then it has no effect unless `--rescan` is supplied.

I suspect that the fix might _not_ be analogous to `--root` (which you dealt with at https://github.com/ESGF/esgf-prepare/commit/563244613ac378c113c331507fb34e0c35a20ef2#diff-8ca9959c19bccb29e2032643860bbca2). If `--root` changes, then it is reasonable to rescan, but if `--commands-file` changes then in principle it is not necessary to rescan.

**Comment by glevava** [comment]
I agree with you but even if the `--command-file` option is part of the tree file, it's not in the controlled arguments that trigger a rescan if changed. Consequently, if this option changes between to `esgprep drs` actions without other argument changes, it shouldn't rescan the files.

**Comment by alaniwi** [comment]
It shouldn't rescan the files - agreed - but what happens at the moment is that any changes are completely ignored (for example, you run without `--commands-file` and it writes to stdout, then you run again with the option but it still writes to stdout).

**Comment by glevava** [comment]
Mmm. Ok that's not the expected behavior. I'll investigate today. The fix will be for the DC2... sorry : /

**Comment by alaniwi** [comment]
No hurry.

**Comment by glevava** [comment]
I got it. It's fixed. In fact the `commands_file` file has to be part of the DRS Tree object to know where to write the command lines output. So it was always restore to its original value unless if `--rescan` is submitted.

**Comment by alaniwi** [comment]
Thanks.
