### ISSUE TITLE
Tags missing and issue with publishing CORDEX data

### ISSUE THREAD

**Issue by pchengi** [ESGF/esgf-prepare#18]
Hi, 

I see that only the latest tags seem to be be maintained for esgf-prepare; please don't delete old tags, as they provide a means of keeping track of the point where the last release pointed to.  I cut ESGF 2.6.1 with esgf-prepare v2.7.33 2018-16-01, and everything seemed fine there. I'm prepping ESGF 2.6.2 and I seem to see some issues with handling of CORDEX data in the latest version (v2.7.35).  I'm getting the following error:

````
(esgf-pub) [root@esg-idx esgcet]# esgprep mapfile --project cordex /esg/data/datapool1/
Mapfile(s) generation: 100% | 1/1 files
Scan errors: 1 (see /esg/config/esgcet/esgprep-20180204-021049-7327.err)
(esgf-pub) [root@esg-idx esgcet]# cat /esg/config/esgcet/esgprep-20180204-021049-7327.err
ERROR      2018-02-04 02:10:49,862 /esg/data/datapool1/cordexdata/cordex/output/AFR-44/SMHI/CCCma-CanESM2/historical/r0i0p0/SMHI-RCA4/v1/fx/orog/v20130927/orog_AFR-44_CCCma-CanESM2_historical_r0i0p0_SMHI-RCA4_v1_fx.nc skipped
NoConfigOption: Option not found
<option: 'rcm_name_map'>
<section: 'project:cordex'>
<file: '/esg/config/esgcet/esg.cordex.ini'>
````

**Comment by pchengi** [comment]
You can reproduce this error by installing ESGF 2.6.0-devel. (this is the test channel, and it's the version prepped for 2.6.2).

**Comment by glevava** [comment]
I just started using tags. No tags existed before for old esgprep version.

**Comment by glevava** [comment]
Regarding your error, it's a side-effet of the project case that is now "free" to be upper/lower/mixcase... as it is recommended by Karl T. for CMIP6.
I just realize that CORDEX (and tied projects as CORDEX-Adjust) is the only project to get "project" as additional key in the maptable of the esg.cordex.ini file.
For instance, `domain_description_map` is defined as `map(project, domain : domain_description)`. Here the "project" key is useless and is the error source you encounter.
I can add a particular fix for CORDEX into esgprep but I'd like to suggest to modify the esg.cordex.ini maptable by removing "cordex" lowercase from maptable keys.
What do you think?
