### ISSUE TITLE
Feature request: esgmapfile to use table of checksums

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-prepare#26]
@glevava Not urgent, but when you have the time...

A nice feature for `esgmapfile` would be if the user can supply a table of known checksums, so that if the node administrator already has the checksums for any reason, then the mapfile generation can avoid the most expensive step.  (A possible use case for us would be to pre-compute checksums using our parallel cluster.)

For example: `--checksums-from my_checksums_file`

where `my_checksums_file` is in the same format as the output of the command-line `sha256sum` or `md5sum` command:

```
checksum_1  /path/to/file1.nc
checksum_2  /path/to/file2.nc
```

It could then use the known checksum instead of computing it. But if either of the following two conditions apply (for a given data file), then it can issue a warning and fall back to compute the checksum for that file as normal:

* the path is not found in the checksums file

* the claimed checksum does not match an appropriate pattern:
  * `^[0-9a-f]{32}$` for md5sum
  * `^[0-9a-f]{64}$` for sha256sum

Thank you.

**Comment by glevava** [comment]
Nice to have ! Probably not too hard to implement and you already think the whole behavior ; ) Will be part of the 2.8.1. : )

**Comment by alaniwi** [comment]
Thanks.

**Comment by alaniwi** [comment]
To answer your question asked on Slack: _"Should we check the file path in the checksum file still exist or not?"_ - I envisage that the directory would still be scanned in order to determine which data files to include, but at each place where the checksum of a file is needed, it is looked up from the checksum file with fallback to evaluating it, as described above.  If any files listed in the checksum file do not exist, their checksum is never needed, so effectively the line is ignored.

In terms of implementation, possibly you could start by parsing the checksums file into a dictionary (`{path1:checksum1, ...etc...}`). If some files do not exist, the checksum will be stored in the directory but never referenced, so will have no effect on the output.

**Comment by glevava** [comment]
Ok, that's the way I implemented it. Sounds good !
