### ISSUE TITLE
in esgmapfile, do not skip "hidden" directories which are part of the specified path

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-prepare#37]
In scanning inside `esgmapfile`, if any element of the path to a data file begins with a `.`, then that file is skipped.

It is reasonable that if a "hidden" file or directory (starting with `.`) is encountered during recursion below the starting directory, then this directory should be skipped. However, if a "hidden" directory is part of the leading part of the path that is specified explicitly on the command line, then it can be assumed that the user intends to scan the directory, so files should should not be skipped only for this reason (although they could still be skipped for some other reason, including where another hidden element is found during recursion).

**Comment by glevava** [comment]
Good catch ! I agree. I will add this support in the next release. Thanks !

**Comment by alaniwi** [comment]
Thanks. I think that this should apply equally also to any other filters specified with `--exclude-file` option: they should only apply to the relative part of the path, not the leading directory.

**Comment by alaniwi** [comment]
Just noting here that a partial workaround is available at present:
```
--ignore-dir '^.*/files.*$'
```
but this will mean that _all_ hidden files get processed, so it is not ideal.

**Comment by glevava** [comment]
I already apply the following fix in the next ongoing release:
