### ISSUE TITLE
Conflicting with cdf2cim, when installed second

### ISSUE THREAD

**Issue by nathanlcarlson** [ESGF/esgf-prepare#42]
Hello, I am a bit new to ESGF. I joined the ESGF-Installer project a few weeks ago. In testing I have encountered a versioning conflict between components being installed via `pip`. I documented [the issue](https://github.com/ESGF/esgf-installer/issues/507) on the Installer page, but I can't think of a good way to resolve it within the Installer. It also may be of interest to this project as well.
The gist is this (copied from Installer issue), after running `python setup.py install` in the esg-publisher repository, which has `esgprep` as a dependency.
```
...
Installed /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.4.9-py2.7.egg
Processing dependencies for esgcet==3.4.9
error: netCDF4 1.4.1 is installed but netCDF4==1.4.0 is required by set(['esgprep'])
```
The problem is that `cdf2cim` has the following requirement in its `setup.py`
```
'netCDF4>=1.2.1'
```
and `esgprep` has this requirement in its `setup.py`
```
'netCDF4==1.4.0'
```
So when `pip` gets `netCDF4` for `cdf2cim` it gets the latest version that satisfies the requirement, in this case `1.4.1` which was released August 9, 2018.

Since `cdf2cim` is installed before `esgprep` (seperate pip install commands), there is this resulting conflict. Of course, the installation of the components could be done at the same time, or in reverse order and if that is the work around you would like us to do that is fine with me. You may consider `"netCDF4>=1.4.0"` if that does not compromise the reliability of your component. If this is our problem to deal with that is perfectly fine as well. Thanks!

**Comment by glevava** [comment]
Hi, this is a `cdf2cim` issue. The ESGF stack requires to set the full version of all dependencies and netCDF==1.4.1 has been decided to be compliant between other ESGF components (esgprep, publisher). I'll ask to `cdf2cim` developers to fix it.
Thanks for catching this.

**Comment by nathanlcarlson** [comment]
@glevava No problem, sounds good! Will you be updating your requirement to `netCDF4==1.4.1` then, as it has been decided to be compliant between ESGF components?
