### ISSUE TITLE
command to test dataset ID validity

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-prepare#44]
**FEATURE REQUEST**

It would be very useful to have a command in esgprep to test the validity of a dataset ID against the rules in the project ini file. At CEDA we would like to use this as the first stage or our ingestion / publication pipeline, so that if data is provided with an invalid dataset ID, then it is rejected at an early stage.

Example command line might be:
```
esgvalidate_id --project <project> [-i <ini_directory>] <dataset_id>
```
but perhaps instead it might be a sub-option of some existing program (I'm not sure which -- maybe `esgdrs` or `esgcheckvocab`).

This should test whether `<dataset_id>` (which should include the `.v<version>` at the end) is valid - with the correct format and with valid facet values.

I suggest that in this case the terminal output could be human-readable, but that there should be a process exit status that can be captured by a calling script.

There are various possible conditions in principle:

- dataset ID is valid
- dataset ID is invalid (but ini file is good)
- ini file is invalid (e.g. cannot be read or a compulsory option is missing)
- bad command line usage
- miscellaneous error (e.g. uncaught exceptions)

I do not think it is necessary to have separate exit statuses for all these conditions. The most important is to have:
- **0 - dataset ID valid**
- **non-zero - all other cases**. 

The next level enhancement which _might_ be useful would be to assign a separate exit status to an invalid ID:
- 0 - dataset ID is valid
- 2 - dataset ID is invalid (but ini file is good)
- 1 - all other cases

although probably at CEDA we would only do automated checks for succeed/fail status (as a boolean), and if we need to distinguish between the different nuances of "fail" we would inspect the human-readable output in the logs.

Many thanks.

**Comment by glevava** [comment]
esgcheckvocab is able to parly do the job. Your need is typically related to controlled vocabulary, not especially on data management (which is the purpose of esgprep).
You should have a look on the pyessv library : [``](https://github.com/ES-DOC/pyessv/blob/master/notebooks/pyessv-and-cmip6.ipynb)
We want to raise a discussion around such a feature and centralized CV at the F2F.
Let me know if pyessv can do want you need (only CMIP5, CMIP6 and CORDEX are currently supported) if not I can think about a new esgprep feature but I would avoid duplicate the efforts ; )
