### ISSUE TITLE
requests version

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-prepare#49]
`requests` is at 2.20.1.  Can the dependency be updated?

https://github.com/ESGF/esgf-prepare/blob/e3e2184266f93fa9dae55c542fb8a85bd4b9dc90/setup.py#L71

Thanks.

**Comment by glevava** [comment]
Only if this is compliant with the other ESGF components... I don't want to cut a new release leading to a new version conflict among dependencies.

**Comment by alaniwi** [comment]
Agreed. It was a question for consideration, rather than a definite request.

**Comment by glevava** [comment]
In agreement with the ESGF installation working team, the esgprep `requests` version will follow specifications from the `esg-init` file to avoid any conflicts during ESGF installation.
