### ISSUE TITLE
"esgmapfile show" attempts filesystem writes (and can fail due a to race condition)

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-prepare#56]
`esgmapfile show` failed because it was attempting some kind of cleanup at the same time that there was a transient file (`...map.part`) in the same mapfile directory because another process was running `esgmapfile make` at the time.

Below is an extract from the log (with local paths edited).  Note that the filename of `CMIP6.CFMIP.IPSL.IPSL-CM6A-LR.aqua-control.r1i1p1f1.Amon.huss.gr.v20180912.map.part` which it is complaining about relates to a different dataset ID from the one given as argument to `esgmapfile show` (the `prsn` one). The modification timestamp on the completed mapfile (`CMIP6.CFMIP.IPSL.IPSL-CM6A-LR.aqua-control.r1i1p1f1.Amon.huss.gr.v20180912.map`) confirms that it was being created at the same time that the `esgmapfile show` was being run.

```
2019-03-06 22:13:36 INFO     command failed

   esgmapfile show --quiet --project cmip6 -i /path/to/ini_dir --outdir /path/to/out_dir --dataset-id CMIP6.CFMIP.IPSL.IPSL-CM6A-LR.aqua-control-lwoff.r1i1p1f1.Amon.prsn.gr.v20180928
   status 1
   stdout 
   stderr Traceback (most recent call last):
  File "/path/to/conda_env/bin/esgmapfile", line 11, in <module>
    load_entry_point('esgprep==2.9.5', 'console_scripts', 'esgmapfile')()
  File "/path/to/conda_env/lib/python2.7/site-packages/esgprep/esgmapfile.py", line 244, in main
    run(args)
  File "/path/to/conda_env/lib/python2.7/site-packages/esgprep/mapfile/main.py", line 265, in run
    with ProcessingContext(args) as ctx:
  File "/path/to/conda_env/lib/python2.7/site-packages/esgprep/mapfile/context.py", line 56, in __init__
    self.clean()
  File "/path/to/conda_env/lib/python2.7/site-packages/esgprep/mapfile/context.py", line 140, in clean
    os.remove(os.path.join(root, filename))
OSError: [Errno 2] No such file or directory: '/path/to/mapfile_dir/cmip6/CMIP6/CFMIP/IPSL/IPSL-CM6A-LR/CMIP6.CFMIP.IPSL.IPSL-CM6A-LR.aqua-control.r1i1p1f1.Amon.huss.gr.v20180912.map.part'
)
```

This was a one-off failure on a busy server, when other similar commands were completing successfully.  So the race condition is rare.  But in any case, the `esgmapfile show` should not be attempting any filesystem writes at all -- it should simply report the location of the mapfile implied by the ini file and the dataset ID.

Thanks.

**Comment by glevava** [comment]
Hi @alaniwi I modified the handler context accordingly. See commit https://github.com/ESGF/esgf-prepare/commit/501ffc59225229d5ff1b551840e84d43a378bbff
I didn't cut a new release now but you can simply modify the line in your local code.

**Comment by alaniwi** [comment]
@glevava Thanks.
