### ISSUE TITLE
Can conda install due to missing package

### ISSUE THREAD

**Issue by sterlingbaldwin** [ESGF/esgf-prepare#62]
The meta.yml lists esgf-config-parser as a required package, but that package is not available on conda, subsequently this package cannot be installed via conda.

**Comment by glevava** [comment]
Because the package name is `esgconfigparser` not `esgf-config-parser `. It's available on pip not through conda.

**Comment by sterlingbaldwin** [comment]
If a dependency of a package isnt available on conda, there's no way to specify that it should find it on pip and thus it cannot be installed. I would love for conda to have a way of finding packages on pip but as far as I know there's no way of doing so. If you're not going to support distributing the package with conda you should probably just remove the "recipe" directory.

**Comment by glevava** [comment]
ok. I'll see in the next release as:
- the ESGFConfigParser library won't be used anymore in esgprep
- but I cannot support a proper installation through conda.

Consequently, I will see if I remove the `recipe` directory or not.
