### ISSUE TITLE
multiple esgmapfile on separate host, shared filesystem

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-prepare#73]
To parallelize generation, I run esgmapfile on two servers that write to the same loc on gpfs.  This seems to create a problem as I observe occasional failures.  I'm guessing that temp files get written and the external process cleans them inadvertently.   I will consider a workaround, but its going to be a bit inconvenient.

**Comment by glevava** [comment]
Hi @sashakames to run esgmapfile with several paralell instances please use the `—no-cleanup` flag on the command-line. This will disable the cleanup of temp mapfile if the processes write in the same destination folder.

**Comment by sashakames** [comment]
Thank you @glevava !
